from typing import Any, Dict, List


CATALOG: Dict[str, List[Dict[str, Any]]] = {
    "providers": [
        {
            "id": "gemini",
            "name": "Google Gemini",
            "category": "provider_api",
            "adapter": "openai",
            "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
            "api_key_env": "GEMINI_API_KEY",
            "docs_url": "https://aistudio.google.com/app/apikey",
        },
        {
            "id": "cohere",
            "name": "Cohere",
            "category": "provider_api",
            "adapter": "cohere",
            "base_url": "https://api.cohere.com/v2",
            "api_key_env": "COHERE_API_KEY",
            "docs_url": "https://dashboard.cohere.com/api-keys",
        },
        {
            "id": "mistral",
            "name": "Mistral AI",
            "category": "provider_api",
            "adapter": "openai",
            "base_url": "https://api.mistral.ai/v1",
            "api_key_env": "MISTRAL_API_KEY",
            "docs_url": "https://console.mistral.ai/api-keys",
        },
        {
            "id": "zhipu",
            "name": "Zhipu AI",
            "category": "provider_api",
            "adapter": "openai",
            "base_url": "https://open.bigmodel.cn/api/paas/v4",
            "api_key_env": "ZHIPU_API_KEY",
            "docs_url": "https://open.bigmodel.cn/",
        },
        {
            "id": "cerebras",
            "name": "Cerebras",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.cerebras.ai/v1",
            "api_key_env": "CEREBRAS_API_KEY",
            "docs_url": "https://cloud.cerebras.ai/",
        },
        {
            "id": "cloudflare",
            "name": "Cloudflare Workers AI",
            "category": "inference_provider",
            "adapter": "cloudflare_workers_ai",
            "base_url": "https://api.cloudflare.com/client/v4",
            "api_key_env": "CLOUDFLARE_API_TOKEN",
            "account_id_env": "CLOUDFLARE_ACCOUNT_ID",
            "docs_url": "https://developers.cloudflare.com/workers-ai/",
        },
        {
            "id": "github_models",
            "name": "GitHub Models",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://models.inference.ai.azure.com",
            "api_key_env": "GITHUB_TOKEN",
            "docs_url": "https://github.com/marketplace/models",
        },
        {
            "id": "groq",
            "name": "Groq",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.groq.com/openai/v1",
            "api_key_env": "GROQ_API_KEY",
            "docs_url": "https://console.groq.com/keys",
        },
        {
            "id": "huggingface",
            "name": "Hugging Face Serverless Inference",
            "category": "inference_provider",
            "adapter": "huggingface_text_generation",
            "base_url": "https://api-inference.huggingface.co",
            "api_key_env": "HUGGINGFACE_API_KEY",
            "docs_url": "https://huggingface.co/settings/tokens",
        },
        {
            "id": "kilo",
            "name": "Kilo Code",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.kilo.ai/api/gateway",
            "api_key_env": "KILO_API_KEY",
            "docs_url": "https://kilo.ai/",
        },
        {
            "id": "llm7",
            "name": "LLM7.io",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.llm7.io/v1",
            "api_key_env": "LLM7_API_KEY",
            "docs_url": "https://llm7.io/",
        },
        {
            "id": "nvidia_nim",
            "name": "NVIDIA NIM",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://integrate.api.nvidia.com/v1",
            "api_key_env": "NVIDIA_API_KEY",
            "docs_url": "https://build.nvidia.com/",
        },
        {
            "id": "openrouter",
            "name": "OpenRouter",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://openrouter.ai/api/v1",
            "api_key_env": "OPENROUTER_API_KEY",
            "docs_url": "https://openrouter.ai/settings/keys",
        },
        {
            "id": "siliconflow",
            "name": "SiliconFlow",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.siliconflow.cn/v1",
            "api_key_env": "SILICONFLOW_API_KEY",
            "docs_url": "https://cloud.siliconflow.cn/",
        },
    ],
    "models": [
        {
            "id": "gemini-2.5-pro",
            "provider_id": "gemini",
            "context_length": 1048576,
            "max_output_tokens": 65536,
            "performance_tier": "high",
            "scenarios": ["reasoning", "agentic", "generation"],
            "quality_score": 9.7,
            "speed_score": 6.0,
            "rate_limit": "5 RPM / 25 RPD",
            "modality": "text",
        },
        {
            "id": "gemini-2.5-flash",
            "provider_id": "gemini",
            "context_length": 1048576,
            "max_output_tokens": 65536,
            "performance_tier": "medium",
            "scenarios": ["generation", "agentic", "vision"],
            "quality_score": 8.8,
            "speed_score": 8.8,
            "rate_limit": "10-15 RPM",
            "modality": "text_vision",
        },
        {
            "id": "command-r",
            "provider_id": "cohere",
            "context_length": 131072,
            "max_output_tokens": 4096,
            "performance_tier": "medium",
            "scenarios": ["generation", "agentic"],
            "quality_score": 7.8,
            "speed_score": 7.0,
            "rate_limit": "20 RPM",
            "modality": "text",
        },
        {
            "id": "mistral-small-latest",
            "provider_id": "mistral",
            "context_length": 131072,
            "max_output_tokens": 32768,
            "performance_tier": "medium",
            "scenarios": ["generation", "coding"],
            "quality_score": 8.0,
            "speed_score": 8.1,
            "rate_limit": "1 req/s",
            "modality": "text",
        },
        {
            "id": "glm-4.5-air",
            "provider_id": "zhipu",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "medium",
            "scenarios": ["generation", "reasoning"],
            "quality_score": 8.0,
            "speed_score": 7.2,
            "rate_limit": "provider-specific",
            "modality": "text",
        },
        {
            "id": "gpt-oss-120b",
            "provider_id": "cerebras",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["reasoning", "generation", "agentic"],
            "quality_score": 9.0,
            "speed_score": 9.8,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "qwen-3-235b-a22b-instruct-2507",
            "provider_id": "cerebras",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["reasoning", "coding", "generation"],
            "quality_score": 9.1,
            "speed_score": 9.5,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
            "provider_id": "cloudflare",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["generation", "agentic"],
            "quality_score": 8.8,
            "speed_score": 8.5,
            "rate_limit": "10K neurons/day",
            "modality": "text",
        },
        {
            "id": "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
            "provider_id": "cloudflare",
            "context_length": 32768,
            "max_output_tokens": 8192,
            "performance_tier": "medium",
            "scenarios": ["reasoning"],
            "quality_score": 8.3,
            "speed_score": 7.4,
            "rate_limit": "10K neurons/day",
            "modality": "text",
        },
        {
            "id": "gpt-4.1",
            "provider_id": "github_models",
            "context_length": 1048576,
            "max_output_tokens": 32768,
            "performance_tier": "high",
            "scenarios": ["generation", "coding", "agentic"],
            "quality_score": 9.5,
            "speed_score": 7.8,
            "rate_limit": "10 RPM / 50 RPD",
            "modality": "text",
        },
        {
            "id": "gpt-4.1-mini",
            "provider_id": "github_models",
            "context_length": 1048576,
            "max_output_tokens": 32768,
            "performance_tier": "medium",
            "scenarios": ["generation", "coding", "agentic"],
            "quality_score": 8.9,
            "speed_score": 8.7,
            "rate_limit": "15 RPM / 150 RPD",
            "modality": "text",
        },
        {
            "id": "o4-mini",
            "provider_id": "github_models",
            "context_length": 204800,
            "max_output_tokens": 100000,
            "performance_tier": "high",
            "scenarios": ["reasoning", "agentic"],
            "quality_score": 9.2,
            "speed_score": 7.5,
            "rate_limit": "10 RPM / 50 RPD",
            "modality": "text",
        },
        {
            "id": "DeepSeek-R1",
            "provider_id": "github_models",
            "context_length": 65536,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["reasoning"],
            "quality_score": 9.0,
            "speed_score": 7.0,
            "rate_limit": "15 RPM / 150 RPD",
            "modality": "text",
        },
        {
            "id": "llama-3.3-70b-versatile",
            "provider_id": "groq",
            "context_length": 131072,
            "max_output_tokens": 32768,
            "performance_tier": "high",
            "scenarios": ["generation", "agentic"],
            "quality_score": 8.9,
            "speed_score": 9.8,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "qwen3-32b",
            "provider_id": "groq",
            "context_length": 131072,
            "max_output_tokens": 131072,
            "performance_tier": "medium",
            "scenarios": ["coding", "generation"],
            "quality_score": 8.4,
            "speed_score": 9.7,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "kimi-k2-instruct",
            "provider_id": "groq",
            "context_length": 262144,
            "max_output_tokens": 262144,
            "performance_tier": "high",
            "scenarios": ["agentic", "generation"],
            "quality_score": 8.9,
            "speed_score": 9.2,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "deepseek-r1-distill-70b",
            "provider_id": "groq",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "medium",
            "scenarios": ["reasoning"],
            "quality_score": 8.5,
            "speed_score": 9.0,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "meta-llama/Meta-Llama-3.1-8B-Instruct",
            "provider_id": "huggingface",
            "context_length": 131072,
            "max_output_tokens": 4096,
            "performance_tier": "low",
            "scenarios": ["generation"],
            "quality_score": 6.8,
            "speed_score": 6.4,
            "rate_limit": "~1000 RPD",
            "modality": "text",
        },
        {
            "id": "Qwen/Qwen2.5-7B-Instruct",
            "provider_id": "huggingface",
            "context_length": 131072,
            "max_output_tokens": 4096,
            "performance_tier": "low",
            "scenarios": ["coding", "generation"],
            "quality_score": 6.9,
            "speed_score": 6.2,
            "rate_limit": "~1000 RPD",
            "modality": "text",
        },
        {
            "id": "nvidia/nemotron-3-super-120b-a12b:free",
            "provider_id": "kilo",
            "context_length": 262144,
            "max_output_tokens": 32768,
            "performance_tier": "high",
            "scenarios": ["reasoning", "generation"],
            "quality_score": 8.8,
            "speed_score": 7.4,
            "rate_limit": "~200 req/hr",
            "modality": "text",
        },
        {
            "id": "x-ai/grok-code-fast-1:optimized:free",
            "provider_id": "kilo",
            "context_length": 131072,
            "max_output_tokens": 16384,
            "performance_tier": "medium",
            "scenarios": ["coding"],
            "quality_score": 8.2,
            "speed_score": 8.8,
            "rate_limit": "~200 req/hr",
            "modality": "text",
        },
        {
            "id": "deepseek-r1-0528",
            "provider_id": "llm7",
            "context_length": 65536,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["reasoning"],
            "quality_score": 8.8,
            "speed_score": 8.0,
            "rate_limit": "30 RPM",
            "modality": "text",
        },
        {
            "id": "qwen2.5-coder-32b",
            "provider_id": "llm7",
            "context_length": 131072,
            "max_output_tokens": 16384,
            "performance_tier": "medium",
            "scenarios": ["coding"],
            "quality_score": 8.1,
            "speed_score": 8.3,
            "rate_limit": "30 RPM",
            "modality": "text",
        },
        {
            "id": "meta/llama-3.1-70b-instruct",
            "provider_id": "nvidia_nim",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["generation", "agentic"],
            "quality_score": 8.8,
            "speed_score": 7.8,
            "rate_limit": "40 RPM",
            "modality": "text",
        },
        {
            "id": "deepseek/deepseek-r1-0528:free",
            "provider_id": "openrouter",
            "context_length": 163840,
            "max_output_tokens": 163840,
            "performance_tier": "high",
            "scenarios": ["reasoning"],
            "quality_score": 9.0,
            "speed_score": 7.6,
            "rate_limit": "20 RPM / 200 RPD",
            "modality": "text",
        },
        {
            "id": "qwen/qwen3.6-plus:free",
            "provider_id": "openrouter",
            "context_length": 1048576,
            "max_output_tokens": 65536,
            "performance_tier": "high",
            "scenarios": ["generation", "agentic"],
            "quality_score": 8.9,
            "speed_score": 7.7,
            "rate_limit": "20 RPM / 200 RPD",
            "modality": "text",
        },
        {
            "id": "qwen/qwen3-coder-480b-a35b:free",
            "provider_id": "openrouter",
            "context_length": 262144,
            "max_output_tokens": 32768,
            "performance_tier": "high",
            "scenarios": ["coding"],
            "quality_score": 9.0,
            "speed_score": 7.1,
            "rate_limit": "20 RPM / 200 RPD",
            "modality": "text",
        },
        {
            "id": "openai/gpt-oss-120b:free",
            "provider_id": "openrouter",
            "context_length": 131072,
            "max_output_tokens": 131072,
            "performance_tier": "high",
            "scenarios": ["reasoning", "generation"],
            "quality_score": 8.8,
            "speed_score": 7.4,
            "rate_limit": "20 RPM / 200 RPD",
            "modality": "text",
        },
        {
            "id": "Qwen/Qwen3-8B",
            "provider_id": "siliconflow",
            "context_length": 131072,
            "max_output_tokens": 131072,
            "performance_tier": "low",
            "scenarios": ["generation", "coding"],
            "quality_score": 7.1,
            "speed_score": 8.4,
            "rate_limit": "1000 RPM / 50K TPM",
            "modality": "text",
        },
        {
            "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
            "provider_id": "siliconflow",
            "context_length": 131072,
            "max_output_tokens": 16384,
            "performance_tier": "low",
            "scenarios": ["reasoning"],
            "quality_score": 7.3,
            "speed_score": 8.2,
            "rate_limit": "1000 RPM / 50K TPM",
            "modality": "text",
        },
    ],
}
