from typing import Any, Dict, List


CATALOG: Dict[str, List[Dict[str, Any]]] = {
    "providers": [
        {
            "id": "gemini",
            "name": "Google Gemini",
            "category": "provider_api",
            "adapter": "openai",
            "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
            "api_key_env": "GEMINI_API_KEY",
            "docs_url": "https://aistudio.google.com/app/apikey",
            "setup_reference": "provider-apis.md",
            "auth_hint": "Google AI Studio API key",
            "example_model": "gemini-2.5-flash",
            "environment_variables": ["GEMINI_API_KEY"],
            "key_steps": [
                "Open Google AI Studio and create an API key.",
                "Attach the key to a Google Cloud project if prompted.",
                "Use the OpenAI-compatible base URL from the guide.",
            ],
            "notes": [
                "Free tier is unavailable in the EEA, UK, and Switzerland.",
                "OpenAI-compatible base URL ends with /v1beta/openai/.",
            ],
        },
        {
            "id": "cohere",
            "name": "Cohere",
            "category": "provider_api",
            "adapter": "openai",
            "base_url": "https://api.cohere.com/v2",
            "api_key_env": "CO_API_KEY",
            "docs_url": "https://dashboard.cohere.com/api-keys",
            "setup_reference": "provider-apis.md",
            "auth_hint": "Cohere trial API key",
            "example_model": "command-a-03-2025",
            "environment_variables": ["CO_API_KEY"],
            "key_steps": [
                "Create a Cohere account and generate a trial API key.",
                "Use the documented OpenAI-compatible base URL.",
            ],
            "notes": [
                "The setup guide uses CO_API_KEY as the env var.",
                "Trial tier is documented at 1K requests/month.",
            ],
        },
        {
            "id": "mistral",
            "name": "Mistral AI",
            "category": "provider_api",
            "adapter": "openai",
            "base_url": "https://api.mistral.ai/v1",
            "api_key_env": "MISTRAL_API_KEY",
            "docs_url": "https://console.mistral.ai/api-keys",
            "setup_reference": "provider-apis.md",
            "auth_hint": "Mistral API key",
            "example_model": "mistral-small-latest",
            "environment_variables": ["MISTRAL_API_KEY"],
            "key_steps": [
                "Create a Mistral console account and generate an API key.",
                "Use the OpenAI-compatible v1 endpoint.",
            ],
            "notes": [
                "~1 request/second and ~1B tokens/month on the free plan per the guide.",
            ],
        },
        {
            "id": "zhipu",
            "name": "Zhipu AI",
            "category": "provider_api",
            "adapter": "openai",
            "base_url": "https://open.bigmodel.cn/api/paas/v4",
            "api_key_env": "ZHIPU_API_KEY",
            "docs_url": "https://open.bigmodel.cn/",
            "setup_reference": "provider-apis.md",
            "auth_hint": "Zhipu API key",
            "example_model": "glm-4.7-flash",
            "environment_variables": ["ZHIPU_API_KEY"],
            "key_steps": [
                "Create a Zhipu account and generate an API key.",
                "Some regions may require a Chinese phone number for signup.",
            ],
            "notes": [
                "The reference guide lists GLM-4.7-Flash, GLM-4.5-Flash, and GLM-4.6V-Flash.",
            ],
        },
        {
            "id": "github_models",
            "name": "GitHub Models",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://models.inference.ai.azure.com",
            "api_key_env": "GITHUB_TOKEN",
            "docs_url": "https://github.com/marketplace/models",
            "setup_reference": "inference-providers.md",
            "auth_hint": "Fine-grained GitHub token with Models permission",
            "example_model": "gpt-4o",
            "environment_variables": ["GITHUB_TOKEN"],
            "key_steps": [
                "Create a fine-grained personal access token with the Models permission.",
                "Use the Azure-hosted OpenAI-compatible base URL.",
            ],
            "notes": [
                "The guide explicitly calls for a fine-grained token with Models permission.",
            ],
        },
        {
            "id": "nvidia_nim",
            "name": "NVIDIA NIM",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://integrate.api.nvidia.com/v1",
            "api_key_env": "NVIDIA_API_KEY",
            "docs_url": "https://build.nvidia.com/",
            "setup_reference": "inference-providers.md",
            "auth_hint": "NVIDIA NIM API key",
            "example_model": "meta/llama-3.3-70b-instruct",
            "environment_variables": ["NVIDIA_API_KEY"],
            "key_steps": [
                "Create or sign in to an NVIDIA developer account.",
                "Pick a model and click Get API Key.",
            ],
            "notes": [
                "The setup guide advertises roughly 40 RPM and no daily token cap.",
            ],
        },
        {
            "id": "groq",
            "name": "Groq",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.groq.com/openai/v1",
            "api_key_env": "GROQ_API_KEY",
            "docs_url": "https://console.groq.com/keys",
            "setup_reference": "inference-providers.md",
            "auth_hint": "Groq API key",
            "example_model": "llama-3.3-70b-versatile",
            "environment_variables": ["GROQ_API_KEY"],
            "key_steps": [
                "Create a Groq account and generate an API key in the console.",
            ],
            "notes": [
                "The setup guide emphasizes high rate limits and fast inference.",
            ],
        },
        {
            "id": "cerebras",
            "name": "Cerebras",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.cerebras.ai/v1",
            "api_key_env": "CEREBRAS_API_KEY",
            "docs_url": "https://cloud.cerebras.ai/",
            "setup_reference": "inference-providers.md",
            "auth_hint": "Cerebras Cloud API key",
            "example_model": "gpt-oss-120b",
            "environment_variables": ["CEREBRAS_API_KEY"],
            "key_steps": [
                "Create a Cerebras Cloud account and issue an API key from API Keys.",
            ],
            "notes": [
                "The setup guide positions Cerebras as an ultra-fast OpenAI-compatible provider.",
            ],
        },
        {
            "id": "cloudflare",
            "name": "Cloudflare Workers AI",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
            "api_key_env": "CLOUDFLARE_API_TOKEN",
            "account_id_env": "CLOUDFLARE_ACCOUNT_ID",
            "docs_url": "https://dash.cloudflare.com/",
            "setup_reference": "inference-providers.md",
            "auth_hint": "Cloudflare API token plus account ID",
            "example_model": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
            "environment_variables": ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID"],
            "key_steps": [
                "Create an API token with Workers AI permission.",
                "Copy the Cloudflare account ID from the dashboard sidebar.",
                "Use the OpenAI-compatible /ai/v1 base URL that includes the account ID.",
            ],
            "notes": [
                "The upstream guide documents the OpenAI-compatible /ai/v1 path, not the low-level /ai/run path.",
            ],
        },
        {
            "id": "llm7",
            "name": "LLM7.io",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.llm7.io/v1",
            "api_key_env": "LLM7_API_KEY",
            "docs_url": "https://token.llm7.io/",
            "setup_reference": "inference-providers.md",
            "auth_hint": "LLM7 token",
            "example_model": "deepseek-r1",
            "environment_variables": ["LLM7_API_KEY"],
            "key_steps": [
                "Get a token from token.llm7.io for higher rate limits.",
            ],
            "notes": [
                "The repo notes that basic access can work without signup, but the setup guide still presents a token-based flow.",
            ],
        },
        {
            "id": "kluster",
            "name": "Kluster AI",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.kluster.ai/v1",
            "api_key_env": "KLUSTER_API_KEY",
            "docs_url": "https://platform.kluster.ai/",
            "setup_reference": "inference-providers.md",
            "auth_hint": "Kluster AI API key",
            "example_model": "deepseek-ai/DeepSeek-R1",
            "environment_variables": ["KLUSTER_API_KEY"],
            "key_steps": [
                "Create a Kluster AI account and generate an API key.",
            ],
            "notes": [
                "The setup guide lists undocumented rate limits.",
            ],
        },
        {
            "id": "openrouter",
            "name": "OpenRouter",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://openrouter.ai/api/v1",
            "api_key_env": "OPENROUTER_API_KEY",
            "docs_url": "https://openrouter.ai/settings/keys",
            "setup_reference": "inference-providers.md",
            "auth_hint": "OpenRouter API key",
            "example_model": "deepseek/deepseek-r1-0528:free",
            "environment_variables": ["OPENROUTER_API_KEY"],
            "key_steps": [
                "Create an OpenRouter account and click Create Key.",
            ],
            "notes": [
                "The guide specifically targets free models with :free suffixes.",
            ],
        },
        {
            "id": "huggingface",
            "name": "Hugging Face",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://router.huggingface.co/v1",
            "api_key_env": "HF_TOKEN",
            "docs_url": "https://huggingface.co/settings/tokens",
            "setup_reference": "inference-providers.md",
            "auth_hint": "HF token with Inference Providers permission",
            "example_model": "meta-llama/Llama-3.3-70B-Instruct",
            "environment_variables": ["HF_TOKEN"],
            "key_steps": [
                "Create a Hugging Face access token with Make calls to Inference Providers permission.",
                "Use the OpenAI-compatible router.huggingface.co/v1 base URL.",
            ],
            "notes": [
                "This is distinct from the legacy api-inference.huggingface.co model endpoint.",
            ],
        },
        {
            "id": "kilo",
            "name": "Kilo Code",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.kilo.ai/api/gateway",
            "api_key_env": "KILO_API_KEY",
            "docs_url": "https://kilo.ai/",
            "setup_reference": "README.md",
            "auth_hint": "Kilo API key",
            "example_model": "nvidia/nemotron-3-super-120b-a12b:free",
            "environment_variables": ["KILO_API_KEY"],
            "key_steps": [
                "Create a Kilo account and generate a gateway key.",
            ],
            "notes": [
                "This provider is in the repo catalog but not in the setup-guide markdown files you pointed to.",
            ],
        },
        {
            "id": "siliconflow",
            "name": "SiliconFlow",
            "category": "inference_provider",
            "adapter": "openai",
            "base_url": "https://api.siliconflow.cn/v1",
            "api_key_env": "SILICONFLOW_API_KEY",
            "docs_url": "https://cloud.siliconflow.cn/",
            "setup_reference": "README.md",
            "auth_hint": "SiliconFlow API key",
            "example_model": "Qwen/Qwen3-8B",
            "environment_variables": ["SILICONFLOW_API_KEY"],
            "key_steps": [
                "Create a SiliconFlow account and generate an API key.",
            ],
            "notes": [
                "This provider is in the repo catalog but not in the setup-guide markdown files you pointed to.",
            ],
        },
    ],
    "models": [
        {
            "id": "gemini-2.5-pro",
            "provider_id": "gemini",
            "context_length": 1048576,
            "max_output_tokens": 65536,
            "performance_tier": "high",
            "scenarios": ["reasoning", "agentic", "generation"],
            "quality_score": 9.7,
            "speed_score": 6.0,
            "rate_limit": "5 RPM / 100 RPD",
            "modality": "text",
        },
        {
            "id": "gemini-2.5-flash",
            "provider_id": "gemini",
            "context_length": 1048576,
            "max_output_tokens": 65536,
            "performance_tier": "medium",
            "scenarios": ["generation", "agentic", "vision"],
            "quality_score": 8.8,
            "speed_score": 8.8,
            "rate_limit": "10 RPM / 250 RPD",
            "modality": "text_vision",
        },
        {
            "id": "gemini-2.5-flash-lite",
            "provider_id": "gemini",
            "context_length": 1048576,
            "max_output_tokens": 65536,
            "performance_tier": "low",
            "scenarios": ["generation", "vision"],
            "quality_score": 7.8,
            "speed_score": 9.0,
            "rate_limit": "15 RPM / 1000 RPD",
            "modality": "text_vision",
        },
        {
            "id": "command-a-03-2025",
            "provider_id": "cohere",
            "context_length": 262144,
            "max_output_tokens": 4096,
            "performance_tier": "high",
            "scenarios": ["generation", "agentic"],
            "quality_score": 8.5,
            "speed_score": 7.0,
            "rate_limit": "20 RPM",
            "modality": "text",
        },
        {
            "id": "command-r-plus",
            "provider_id": "cohere",
            "context_length": 131072,
            "max_output_tokens": 4096,
            "performance_tier": "medium",
            "scenarios": ["generation", "agentic"],
            "quality_score": 7.9,
            "speed_score": 7.0,
            "rate_limit": "20 RPM",
            "modality": "text",
        },
        {
            "id": "mistral-small-latest",
            "provider_id": "mistral",
            "context_length": 131072,
            "max_output_tokens": 32768,
            "performance_tier": "medium",
            "scenarios": ["generation", "coding"],
            "quality_score": 8.0,
            "speed_score": 8.1,
            "rate_limit": "~1 RPS / 500K TPM",
            "modality": "text",
        },
        {
            "id": "mistral-large-latest",
            "provider_id": "mistral",
            "context_length": 262144,
            "max_output_tokens": 262144,
            "performance_tier": "high",
            "scenarios": ["generation", "reasoning", "agentic"],
            "quality_score": 9.0,
            "speed_score": 7.0,
            "rate_limit": "~1 RPS / 500K TPM",
            "modality": "text",
        },
        {
            "id": "codestral-latest",
            "provider_id": "mistral",
            "context_length": 262144,
            "max_output_tokens": 262144,
            "performance_tier": "high",
            "scenarios": ["coding"],
            "quality_score": 8.8,
            "speed_score": 7.4,
            "rate_limit": "~1 RPS / 500K TPM",
            "modality": "text",
        },
        {
            "id": "glm-4.7-flash",
            "provider_id": "zhipu",
            "context_length": 204800,
            "max_output_tokens": 131072,
            "performance_tier": "medium",
            "scenarios": ["generation", "reasoning"],
            "quality_score": 8.2,
            "speed_score": 7.6,
            "rate_limit": "1 concurrent request",
            "modality": "text",
        },
        {
            "id": "glm-4.6v-flash",
            "provider_id": "zhipu",
            "context_length": 131072,
            "max_output_tokens": 4096,
            "performance_tier": "medium",
            "scenarios": ["vision", "generation"],
            "quality_score": 8.0,
            "speed_score": 7.2,
            "rate_limit": "1 concurrent request",
            "modality": "text_vision",
        },
        {
            "id": "gpt-oss-120b",
            "provider_id": "cerebras",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["reasoning", "generation", "agentic"],
            "quality_score": 9.0,
            "speed_score": 9.8,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "qwen-3-235b-a22b-instruct-2507",
            "provider_id": "cerebras",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["reasoning", "coding", "generation"],
            "quality_score": 9.1,
            "speed_score": 9.5,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
            "provider_id": "cloudflare",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["generation", "agentic"],
            "quality_score": 8.8,
            "speed_score": 8.5,
            "rate_limit": "10K neurons/day",
            "modality": "text",
        },
        {
            "id": "@cf/meta/llama-3.2-11b-vision-instruct",
            "provider_id": "cloudflare",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "medium",
            "scenarios": ["vision", "generation"],
            "quality_score": 8.1,
            "speed_score": 8.4,
            "rate_limit": "10K neurons/day",
            "modality": "text_vision",
        },
        {
            "id": "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
            "provider_id": "cloudflare",
            "context_length": 32768,
            "max_output_tokens": 8192,
            "performance_tier": "medium",
            "scenarios": ["reasoning"],
            "quality_score": 8.3,
            "speed_score": 7.4,
            "rate_limit": "10K neurons/day",
            "modality": "text",
        },
        {
            "id": "gpt-4.1",
            "provider_id": "github_models",
            "context_length": 1048576,
            "max_output_tokens": 32768,
            "performance_tier": "high",
            "scenarios": ["generation", "coding", "agentic"],
            "quality_score": 9.5,
            "speed_score": 7.8,
            "rate_limit": "10 RPM / 50 RPD",
            "modality": "text",
        },
        {
            "id": "gpt-4.1-mini",
            "provider_id": "github_models",
            "context_length": 1048576,
            "max_output_tokens": 32768,
            "performance_tier": "medium",
            "scenarios": ["generation", "coding", "agentic"],
            "quality_score": 8.9,
            "speed_score": 8.7,
            "rate_limit": "15 RPM / 150 RPD",
            "modality": "text",
        },
        {
            "id": "gpt-4o",
            "provider_id": "github_models",
            "context_length": 131072,
            "max_output_tokens": 16384,
            "performance_tier": "high",
            "scenarios": ["generation", "vision"],
            "quality_score": 9.2,
            "speed_score": 8.0,
            "rate_limit": "10 RPM / 50 RPD",
            "modality": "text_vision",
        },
        {
            "id": "o4-mini",
            "provider_id": "github_models",
            "context_length": 204800,
            "max_output_tokens": 100000,
            "performance_tier": "high",
            "scenarios": ["reasoning", "agentic"],
            "quality_score": 9.2,
            "speed_score": 7.5,
            "rate_limit": "10 RPM / 50 RPD",
            "modality": "text",
        },
        {
            "id": "DeepSeek-R1",
            "provider_id": "github_models",
            "context_length": 65536,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["reasoning"],
            "quality_score": 9.0,
            "speed_score": 7.0,
            "rate_limit": "15 RPM / 150 RPD",
            "modality": "text",
        },
        {
            "id": "meta/llama-3.3-70b-instruct",
            "provider_id": "nvidia_nim",
            "context_length": 131072,
            "max_output_tokens": 4096,
            "performance_tier": "high",
            "scenarios": ["generation", "agentic"],
            "quality_score": 8.9,
            "speed_score": 7.8,
            "rate_limit": "~40 RPM",
            "modality": "text",
        },
        {
            "id": "nvidia/nemotron-3-super-120b-a12b",
            "provider_id": "nvidia_nim",
            "context_length": 262144,
            "max_output_tokens": 262144,
            "performance_tier": "high",
            "scenarios": ["reasoning", "generation"],
            "quality_score": 8.9,
            "speed_score": 7.9,
            "rate_limit": "~40 RPM",
            "modality": "text",
        },
        {
            "id": "llama-3.3-70b-versatile",
            "provider_id": "groq",
            "context_length": 131072,
            "max_output_tokens": 32768,
            "performance_tier": "high",
            "scenarios": ["generation", "agentic"],
            "quality_score": 8.9,
            "speed_score": 9.8,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "qwen3-32b",
            "provider_id": "groq",
            "context_length": 131072,
            "max_output_tokens": 131072,
            "performance_tier": "medium",
            "scenarios": ["coding", "generation"],
            "quality_score": 8.4,
            "speed_score": 9.7,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "kimi-k2-instruct",
            "provider_id": "groq",
            "context_length": 262144,
            "max_output_tokens": 262144,
            "performance_tier": "high",
            "scenarios": ["agentic", "generation"],
            "quality_score": 8.9,
            "speed_score": 9.2,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "deepseek-r1-distill-70b",
            "provider_id": "groq",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "medium",
            "scenarios": ["reasoning"],
            "quality_score": 8.5,
            "speed_score": 9.0,
            "rate_limit": "30 RPM / 14.4K RPD",
            "modality": "text",
        },
        {
            "id": "deepseek-r1",
            "provider_id": "llm7",
            "context_length": 65536,
            "max_output_tokens": 8192,
            "performance_tier": "high",
            "scenarios": ["reasoning"],
            "quality_score": 8.8,
            "speed_score": 8.0,
            "rate_limit": "30 RPM (120 with token)",
            "modality": "text",
        },
        {
            "id": "qwen2.5-coder-32b",
            "provider_id": "llm7",
            "context_length": 131072,
            "max_output_tokens": 16384,
            "performance_tier": "medium",
            "scenarios": ["coding"],
            "quality_score": 8.1,
            "speed_score": 8.3,
            "rate_limit": "30 RPM (120 with token)",
            "modality": "text",
        },
        {
            "id": "deepseek-ai/DeepSeek-R1",
            "provider_id": "kluster",
            "context_length": 131072,
            "max_output_tokens": 32768,
            "performance_tier": "high",
            "scenarios": ["reasoning"],
            "quality_score": 8.9,
            "speed_score": 7.8,
            "rate_limit": "undocumented",
            "modality": "text",
        },
        {
            "id": "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
            "provider_id": "kluster",
            "context_length": 131072,
            "max_output_tokens": 16384,
            "performance_tier": "high",
            "scenarios": ["generation", "vision"],
            "quality_score": 8.6,
            "speed_score": 8.0,
            "rate_limit": "undocumented",
            "modality": "text_vision",
        },
        {
            "id": "qwen/Qwen3-235B-A22B-Instruct-2507",
            "provider_id": "kluster",
            "context_length": 131072,
            "max_output_tokens": 16384,
            "performance_tier": "high",
            "scenarios": ["coding", "reasoning", "generation"],
            "quality_score": 9.0,
            "speed_score": 7.8,
            "rate_limit": "undocumented",
            "modality": "text",
        },
        {
            "id": "deepseek/deepseek-r1-0528:free",
            "provider_id": "openrouter",
            "context_length": 163840,
            "max_output_tokens": 163840,
            "performance_tier": "high",
            "scenarios": ["reasoning"],
            "quality_score": 9.0,
            "speed_score": 7.6,
            "rate_limit": "20 RPM / 200 RPD",
            "modality": "text",
        },
        {
            "id": "qwen/qwen3.6-plus:free",
            "provider_id": "openrouter",
            "context_length": 1048576,
            "max_output_tokens": 65536,
            "performance_tier": "high",
            "scenarios": ["generation", "agentic"],
            "quality_score": 8.9,
            "speed_score": 7.7,
            "rate_limit": "20 RPM / 200 RPD",
            "modality": "text",
        },
        {
            "id": "qwen/qwen3-coder-480b-a35b:free",
            "provider_id": "openrouter",
            "context_length": 262144,
            "max_output_tokens": 32768,
            "performance_tier": "high",
            "scenarios": ["coding"],
            "quality_score": 9.0,
            "speed_score": 7.1,
            "rate_limit": "20 RPM / 200 RPD",
            "modality": "text",
        },
        {
            "id": "openai/gpt-oss-120b:free",
            "provider_id": "openrouter",
            "context_length": 131072,
            "max_output_tokens": 131072,
            "performance_tier": "high",
            "scenarios": ["reasoning", "generation"],
            "quality_score": 8.8,
            "speed_score": 7.4,
            "rate_limit": "20 RPM / 200 RPD",
            "modality": "text",
        },
        {
            "id": "meta-llama/Llama-3.3-70B-Instruct",
            "provider_id": "huggingface",
            "context_length": 131072,
            "max_output_tokens": 4096,
            "performance_tier": "medium",
            "scenarios": ["generation"],
            "quality_score": 8.2,
            "speed_score": 6.8,
            "rate_limit": "$0.10/month free credits",
            "modality": "text",
        },
        {
            "id": "Qwen/Qwen2.5-72B-Instruct",
            "provider_id": "huggingface",
            "context_length": 131072,
            "max_output_tokens": 8192,
            "performance_tier": "medium",
            "scenarios": ["coding", "generation"],
            "quality_score": 8.1,
            "speed_score": 6.6,
            "rate_limit": "$0.10/month free credits",
            "modality": "text",
        },
        {
            "id": "nvidia/nemotron-3-super-120b-a12b:free",
            "provider_id": "kilo",
            "context_length": 262144,
            "max_output_tokens": 32768,
            "performance_tier": "high",
            "scenarios": ["reasoning", "generation"],
            "quality_score": 8.8,
            "speed_score": 7.4,
            "rate_limit": "~200 req/hr",
            "modality": "text",
        },
        {
            "id": "x-ai/grok-code-fast-1:optimized:free",
            "provider_id": "kilo",
            "context_length": 131072,
            "max_output_tokens": 16384,
            "performance_tier": "medium",
            "scenarios": ["coding"],
            "quality_score": 8.2,
            "speed_score": 8.8,
            "rate_limit": "~200 req/hr",
            "modality": "text",
        },
        {
            "id": "Qwen/Qwen3-8B",
            "provider_id": "siliconflow",
            "context_length": 131072,
            "max_output_tokens": 131072,
            "performance_tier": "low",
            "scenarios": ["generation", "coding"],
            "quality_score": 7.1,
            "speed_score": 8.4,
            "rate_limit": "1000 RPM / 50K TPM",
            "modality": "text",
        },
        {
            "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
            "provider_id": "siliconflow",
            "context_length": 131072,
            "max_output_tokens": 16384,
            "performance_tier": "low",
            "scenarios": ["reasoning"],
            "quality_score": 7.3,
            "speed_score": 8.2,
            "rate_limit": "1000 RPM / 50K TPM",
            "modality": "text",
        },
    ],
}
